SL:
  TRAFIKLAB_API_KEY: "d0a921619ab540dba14f9ee09c82c2ef"
  SITEID: "1302"
  TIME: "20"
  URL: "https://api.sl.se/api2/realtimedepartures.json?key=d0a921619ab540dba14f9ee09c82c2ef&siteid=1302&timewindow=10"